project:
  type: book
  output-dir: docs

book:
  title: "Data Science Workshop"
  author: "Thomas O'Leary"
  date: "Fall 2023"
  chapters:
    - index.qmd
    - tidyverse.qmd
    - data_viz.qmd
    - repro.qmd
    - references.qmd

bibliography: references.bib

from: markdown+emoji

format:
  html:
    theme: 
    - cosmo
    - color.scss



